version: "3.3"
services:
  db:
    image: mysql:8.0.21
    container_name: thiago_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    expose: 
      - 3306
  phpcompile:
    container_name: thiago_phpcompile
    build: 
      context: .
      dockerfile: dockerfile_php
    working_dir: /var/www/api
    volumes: 
      - ../api:/var/www/api
    command: composer install
  php:
    build: 
      context: .
      dockerfile: dockerfile_php
    container_name: thiago_php
    working_dir: /var/www/api
    volumes: 
      - ../api:/var/www/api
      - ../www:/var/www/www
      - ./php/fpm/ini.conf:/usr/local/etc/php-fpm.conf.d.99/ini.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/extra.ini
    links: 
      - db
    depends_on: 
      - db
    restart: always
    expose: 
      - 8000
    ports:
      - 8000:8000
    depends_on: 
      - phpcompile
    command: /bin/bash -c 'php -S 0.0.0.0:8000 -t ./public'
  vue:
    image: node
    container_name: thiago_vue
    volumes: 
      - ../www:/var/www/www
    working_dir: /var/www/www
    command: /bin/bash -c 'npm install && npm run serve'
    expose: 
      - 8080
    ports:
      - 8080:8080