version: "3.3"
services:
  db:
    image: mysql:8.0.21
    container_name: jobsity_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    expose: 
      - 3306
  # phpcompile:
  #   container_name: jobsity_phpcompile
  #   build: 
  #     context: .
  #     dockerfile: dockerfile_php
  #   working_dir: /var/www/api
  #   volumes: 
  #     - ../api:/var/www/api
  #   command: composer install
  # php:
  #   build: 
  #     context: .
  #     dockerfile: dockerfile_php
  #   container_name: jobsity_php
  #   working_dir: /var/www/api
  #   volumes: 
  #     - ../api:/var/www/api
  #     - ../www:/var/www/www
  #     - ./php/fpm/ini.conf:/usr/local/etc/php-fpm.conf.d.99/ini.conf
  #     - ./php/php.ini:/usr/local/etc/php/conf.d/extra.ini
  #   links: 
  #     - db
  #   depends_on: 
  #     - db
  #   # external_links: 
  #   #   - web:api.dev.dev.vidacoop.com.br
  #   #   - web:app.dev.dev.vidacoop.com.br
  #   # restart: always
  #   expose: 
  #     - 8000
  #   ports:
  #     - 8000:8000
  #   depends_on: 
  #     - phpcompile
  #   command: /bin/bash -c 'php -S localhost:8000 -t ./public'
  # vue:
  #   image: node
  #   container_name: jobsity_vue
  #   volumes: 
  #     - ../www:/var/www/www
  #   working_dir: /var/www/www
  #   command: /bin/bash -c 'npm install && npm run serve'
  #   # external_links: 
  #   #   - web:api.dev.dev.vidacoop.com.br
  #   #   - web:app.dev.dev.vidacoop.com.br
  #   expose: 
  #     - 8080
  #   ports:
  #     - 8080:8080
  # # web:
  # #   image: nginx:1.16.1
  # #   container_name: jobsity_web
  # #   restart: always
  # #   working_dir: /var/www/
  # #   volumes:
  # #     - ../api:/var/www/api
  # #     - ../www:/var/www/www
  # #     - ./php/fpm/ini.conf:/usr/local/etc/php-fpm.conf.d.99/ini.conf
  # #     - ./php/php.ini:/usr/local/etc/php/conf.d/extra.ini
  # #   links:
  # #     - php
  # #     - vue
  # #   depends_on:
  # #     - php
  # #     - vue
  # #   ports:
  # #     - 80:80
  # #   expose: 
  # #     - 80
  # #   command: /bin/bash -c "em /etc/nginx/conf.d/default & exec nginx -g 'daemon off;'"
