FROM php:7.4.8-fpm

RUN echo 'deb http://httpredir.debian.org/debian jessie contrib' >> /etc/apt/sources.list
RUN echo 'include=etc/php-fpm.conf.d.99/*.conf' >> /usr/local/etc/php-fpm.conf

RUN apt-get update
RUN export DEBIAN_FRONTEND=noninteractive && apt-get install -y --force-yes libssl-dev curl  libcurl4-gnutls-dev libxml2-dev libicu-dev libmcrypt4 libmemcached11 openssl

RUN pecl update-channels

#CONFIGURAÇÕES DO OPCACHE
RUN docker-php-ext-install opcache

#CONFIGURAÇÕES DO APCU
RUN pecl install apcu-5.1.18 && docker-php-ext-enable apcu

#MONGODB Client PHP
RUN pecl install mongodb

#LIBS EXTRAS
RUN apt-get update
RUN apt-get install curl -y
RUN docker-php-ext-install bcmath
RUN apt-get install -y libbz2-dev
RUN docker-php-ext-install bz2
RUN apt-get install -y \
    zlib1g-dev \
    libzip-dev \
    libonig-dev
RUN docker-php-ext-install zip
RUN apt-get install -y libpq-dev
RUN apt-get install -y libicu-dev
RUN docker-php-ext-install intl
RUN pecl install xdebug-2.9.6
RUN docker-php-ext-enable xdebug

#COMPOSER
RUN curl -s https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

#GD
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng16-16
# RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
RUN docker-php-ext-install gd

#PDO
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-install pdo pdo_mysql

EXPOSE 9000
CMD ["php-fpm"]